#!/bin/sh

case "$1" in
  start)
    echo "Starting iwd..."
    mkdir -p /var/lib/iwd
    /usr/libexec/iwd &
    
    echo "Starting kexecboot TUI..."
    # Allow iwd to initialize
    sleep 2
    /usr/bin/kexecboot-tui
    ;;
  stop)
    echo "Stopping iwd..."
    killall iwd
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
