name: Build kexecboot.xyz ISO

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted, linux64, heavy]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Cache Buildroot downloads
        uses: actions/cache@v4
        with:
          path: buildroot/dl
          key: ${{ runner.os }}-buildroot-dl

      - name: Download Buildroot
        run: |
          wget https://buildroot.org/downloads/buildroot-2023.11.1.tar.gz
          tar -xf buildroot-2023.11.1.tar.gz
          mv buildroot-2023.11.1 buildroot

      - name: Configure Buildroot
        run: |
          cd buildroot
          make BR2_EXTERNAL=../buildroot-external kexecboot_defconfig

      - name: Build
        run: |
          cd buildroot
          make -j$(nproc)

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kexecboot-images
          path: buildroot/output/images/
